### ISSUE TITLE
PHP approach

### ISSUE THREAD

**Issue by szepeviktor** [struggle-for-php/sfp-psalm-typed-local-variable-plugin#1]
@sasezaki Do you know https://github.com/sj-i/typist ?

**Comment by sasezaki** [comment]
Yes.

This plugin & typist would sound similar idea of "types of local variables".

But typist is type enforcements, and also need adding typist's method call into any Project codebase.

This plugin propose is find possible bugs as static analysis. And NOT needs adding any method call into codebase.
